### ISSUE TITLE
Refactorizar librería con estares de Python avanzado

### ISSUE THREAD

**Issue by JoseSalamancaCoy** [MakeSens-Data/MakeSensAPI_Python#3]
Refactorizar el código para hacerlo mas legible

**Comment by miguelta281** [comment]
Se refactorizó la librería, pasando de tener 5 funcionalidades, donde al menos dos de estas eran redundantes, a tres que además son escalables a otras variables más allá del material particulado. 

Se redujo de más de 600 líneas de código a aproximadamente 300, usando la guía de estilo pep8 de python.
